apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocp-java-ubi8.fullname" . }}
  labels:
    {{- include "ocp-java-ubi8.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.sport }}
      targetPort: {{ .Values.service.sport }}
      protocol: TCP
      name: https
  selector:
    {{- include "ocp-java-ubi8.selectorLabels" . | nindent 4 }}